# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "http://git.code.oa.com/kuaibao/Specs.git"
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Example
  pod 'Mediator', :path => '../'

end
